# Generated by: tyk-ci/wf-gen
# Generated on: Wed 17 Feb 09:39:45 UTC 2021

# Generation commands:
# ./pr.zsh -title Extra docker files -branch goreleaser/more -p
# m4 -E -DxREPO=tyk-pump


ARG BASE_IMAGE=debian:buster-slim
ARG PORTS
ARG TARBALL

FROM $BASE_IMAGE

RUN apt-get update \
 && apt-get dist-upgrade -y ca-certificates \
 && apt-get autoremove -y

WORKDIR /opt/tyk-pump
COPY $TARBALL .

EXPOSE $PORTS

ENTRYPOINT ["/opt/tyk-pump/tyk-pump" ]
CMD [ "--conf=/opt/tyk-pump/tyk-pump.conf" ]
