

# Generated by: tyk-ci/wf-gen
# Generated on: Thu Feb 24 17:02:50 UTC 2022

# Generation commands:
# ./pr.zsh -p -base TD-883/consolidate-releng-code -branch TD-883/consolidate-releng-code -title internal: Update releng upgrade pump from 1.4.0 -repos tyk-pump
# m4 -E -DxREPO=tyk-pump


data "terraform_remote_state" "integration" {
  backend = "remote"

  config = {
    organization = "Tyk"
    workspaces = {
      name = "base-prod"
    }
  }
}

output "tyk-pump" {
  value = data.terraform_remote_state.integration.outputs.tyk-pump
  description = "ECR creds for tyk-pump repo"
}

output "region" {
  value = data.terraform_remote_state.integration.outputs.region
  description = "Region in which the env is running"
}
