#!/bin/bash



# Generated by: tyk-ci/wf-gen
# Generated on: Wednesday 02 March 2022 07:39:15 AM UTC

# Generation commands:
# ./pr.zsh -title Sync from latest releng templates -branch test/sync-changes -base master -repos tyk-pump -p
# m4 -E -DxREPO=tyk-pump


echo "Creating user and group..."
GROUPNAME="tyk"
USERNAME="tyk"

getent group "$GROUPNAME" >/dev/null || groupadd -r "$GROUPNAME"
getent passwd "$USERNAME" >/dev/null || useradd -r -g "$GROUPNAME" -M -s /sbin/nologin -c "Tyk service user" "$USERNAME"

