#!/bin/bash



# Generated by: tyk-ci/wf-gen
# Generated on: Thu Feb 24 16:00:39 UTC 2022

# Generation commands:
# ./pr.zsh -p -base TD-883/consolidate-releng-code -branch TD-883/consolidate-releng-code -title internal: Update releng after TD-883 consolidation -repos tyk-pump
# m4 -E -DxREPO=tyk-pump


echo "Creating user and group..."
GROUPNAME="tyk"
USERNAME="tyk"

getent group "$GROUPNAME" >/dev/null || groupadd -r "$GROUPNAME"
getent passwd "$USERNAME" >/dev/null || useradd -r -g "$GROUPNAME" -M -s /sbin/nologin -c "Tyk service user" "$USERNAME"

