#!/bin/sh



# Generated by: tyk-ci/wf-gen
# Generated on: Thu Feb 24 16:00:39 UTC 2022

# Generation commands:
# ./pr.zsh -p -base TD-883/consolidate-releng-code -branch TD-883/consolidate-releng-code -title internal: Update releng after TD-883 consolidation -repos tyk-pump
# m4 -E -DxREPO=tyk-pump


if command -V systemctl >/dev/null 2>&1; then
    if [ ! -f /lib/systemd/system/tyk-pump.service ]; then
        cp /opt/tyk-pump/install/inits/systemd/system/tyk-pump.service /lib/systemd/system/tyk-pump.service
    fi
else
    if [ ! -f /etc/init.d/tyk-pump ]; then
        cp /opt/tyk-pump/install/inits/sysv/init.d/tyk-pump /etc/init.d/tyk-pump
    fi
fi
