// Code generated by MockGen. DO NOT EDIT.
// Source: graph_mongo.go

// Package pumps is a generated GoMock package.
package pumps

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockcollectionStore is a mock of collectionStore interface.
type MockcollectionStore struct {
	ctrl     *gomock.Controller
	recorder *MockcollectionStoreMockRecorder
}

// MockcollectionStoreMockRecorder is the mock recorder for MockcollectionStore.
type MockcollectionStoreMockRecorder struct {
	mock *MockcollectionStore
}

// NewMockcollectionStore creates a new mock instance.
func NewMockcollectionStore(ctrl *gomock.Controller) *MockcollectionStore {
	mock := &MockcollectionStore{ctrl: ctrl}
	mock.recorder = &MockcollectionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcollectionStore) EXPECT() *MockcollectionStoreMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockcollectionStore) Insert(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockcollectionStoreMockRecorder) Insert(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockcollectionStore)(nil).Insert), arg0)
}
