# Generated by: tyk-ci/wf-gen
# Generated on: Fri Dec 17 15:28:00 UTC 2021

# Generation commands:
# ./pr.zsh -p -title sync for m4 templates -branch pkr176 -base pkr176 -repos tyk-pump
# m4 -E -DxREPO=tyk-pump


data "terraform_remote_state" "integration" {
  backend = "remote"

  config = {
    organization = "Tyk"
    workspaces = {
      name = "base-prod"
    }
  }
}

output "tyk-pump" {
  value = data.terraform_remote_state.integration.outputs.tyk-pump
  description = "ECR creds for tyk-pump repo"
}

output "region" {
  value = data.terraform_remote_state.integration.outputs.region
  description = "Region in which the env is running"
}
