# Generated by: tyk-ci/wf-gen
# Generated on: Thu 17 Jun 08:26:46 UTC 2021

# Generation commands:
# ./pr.zsh -title releng: [TD-388] fix automated upgrade testing -branch releng/master -repos tyk-identity-broker,tyk-pump,raava
# m4 -E -DxREPO=tyk-pump


data "terraform_remote_state" "integration" {
  backend = "remote"

  config = {
    organization = "Tyk"
    workspaces = {
      name = "base-prod"
    }
  }
}

output "tyk-pump" {
  value = data.terraform_remote_state.integration.outputs.tyk-pump
  description = "ECR creds for tyk-pump repo"
}

output "region" {
  value = data.terraform_remote_state.integration.outputs.region
  description = "Region in which the env is running"
}
