# Generated by: tyk-ci/wf-gen
# Generated on: Thu 29 Apr 04:36:48 UTC 2021

# Generation commands:
# ./pr.zsh -title disable cloudsmith unified manifest -branch releng/arm64 -base releng/arm64 -p
# m4 -E -DxREPO=tyk-pump


data "terraform_remote_state" "integration" {
  backend = "remote"

  config = {
    organization = "Tyk"
    workspaces = {
      name = "base-prod"
    }
  }
}

output "tyk-pump" {
  value = data.terraform_remote_state.integration.outputs.tyk-pump
  description = "ECR creds for tyk-pump repo"
}

output "region" {
  value = data.terraform_remote_state.integration.outputs.region
  description = "Region in which the env is running"
}
