# Generated by: tyk-ci/wf-gen
# Generated on: Thu Jan 20 18:46:58 UTC 2022

# Generation commands:
# ./pr.zsh -base master -branch master-m4-sync -title Sync master with m4 release engineering templates -repos tyk,tyk-pump,tyk-analytics,tyk-identity-broker
# m4 -E -DxREPO=tyk-pump


data "terraform_remote_state" "integration" {
  backend = "remote"

  config = {
    organization = "Tyk"
    workspaces = {
      name = "base-prod"
    }
  }
}

output "tyk-pump" {
  value = data.terraform_remote_state.integration.outputs.tyk-pump
  description = "ECR creds for tyk-pump repo"
}

output "region" {
  value = data.terraform_remote_state.integration.outputs.region
  description = "Region in which the env is running"
}
