# Generated on: Fri 11 Dec 00:40:39 IST 2020

# Generated by: wf-gen from tyk-ci

FROM debian:buster-slim

RUN apt-get update \
 && apt-get dist-upgrade -y --no-install-recommends \
        wget jq curl ca-certificates apt-transport-https gnupg unzip


RUN apt-get autoremove -y 

ADD tyk-pump.tar.gz /opt/tyk-pump

VOLUME ["/conf"]
WORKDIR /opt/tyk-pump

ENTRYPOINT ["/opt/tyk-pump/tyk-pump" ]
CMD [ "--conf=/conf/tyk-pump/tyk-pump.conf" ]

# Local Variables:
# mode: dockerfile
# End:
