#!/bin/bash

# Generated by: tyk-ci/wf-gen
# Generated on: Fri  3 Sep 12:23:42 UTC 2021

# Generation commands:
# ./pr.zsh -title [TT-2932] systemd service restore for deb -base releng/upgrades -branch releng/upgrades -repos tyk-sink,tyk-identity-broker,tyk-pump,raava -p
# m4 -E -DxREPO=tyk-pump


echo "Creating user and group..."
GROUPNAME="tyk"
USERNAME="tyk"

getent group "$GROUPNAME" >/dev/null || groupadd -r "$GROUPNAME"
getent passwd "$USERNAME" >/dev/null || useradd -r -g "$GROUPNAME" -M -s /sbin/nologin -c "Tyk service user" "$USERNAME"

