#!/bin/bash

# Generated by: tyk-ci/wf-gen
# Generated on: Fri 27 Aug 10:56:00 UTC 2021

# Generation commands:
# ./pr.zsh -title [TT-2932] more control over upgrades -branch releng/upgrades -base master
# m4 -E -DxREPO=tyk-pump


echo "Creating user and group..."
GROUPNAME="tyk"
USERNAME="tyk"

getent group "$GROUPNAME" >/dev/null || groupadd -r "$GROUPNAME"
getent passwd "$USERNAME" >/dev/null || useradd -r -g "$GROUPNAME" -M -s /sbin/nologin -c "Tyk service user" "$USERNAME"

