#!/bin/bash

# Generated by: tyk-ci/wf-gen
# Generated on: Thu Jan 27 14:55:24 UTC 2022

# Generation commands:
# ./pr.zsh -p -base master-m4-sync -branch master-m4-sync -title Change commit var to Commit -repos tyk,tyk-pump,tyk-analytics,tyk-identity-broker
# m4 -E -DxREPO=tyk-pump


echo "Creating user and group..."
GROUPNAME="tyk"
USERNAME="tyk"

getent group "$GROUPNAME" >/dev/null || groupadd -r "$GROUPNAME"
getent passwd "$USERNAME" >/dev/null || useradd -r -g "$GROUPNAME" -M -s /sbin/nologin -c "Tyk service user" "$USERNAME"

