#!/bin/sh

# Generated by: tyk-ci/wf-gen
# Generated on: Fri  3 Sep 12:23:42 UTC 2021

# Generation commands:
# ./pr.zsh -title [TT-2932] systemd service restore for deb -base releng/upgrades -branch releng/upgrades -repos tyk-sink,tyk-identity-broker,tyk-pump,raava -p
# m4 -E -DxREPO=tyk-pump


if command -V systemctl >/dev/null 2>&1; then
    if [ ! -f /lib/systemd/system/tyk-pump.service ]; then
	cp /opt/tyk-pump/install/tyk-pump.service /lib/systemd/system/tyk-pump.service
    fi
fi
