#!/bin/sh

# Generated by: tyk-ci/wf-gen
# Generated on: Thu Jan 27 14:55:25 UTC 2022

# Generation commands:
# ./pr.zsh -p -base master-m4-sync -branch master-m4-sync -title Change commit var to Commit -repos tyk,tyk-pump,tyk-analytics,tyk-identity-broker
# m4 -E -DxREPO=tyk-pump


if command -V systemctl >/dev/null 2>&1; then
    if [ ! -f /lib/systemd/system/tyk-pump.service ]; then
        cp /opt/tyk-pump/install/inits/systemd/system/tyk-pump.service /lib/systemd/system/tyk-pump.service
    fi
else
    if [ ! -f /etc/init.d/tyk-pump ]; then
        cp /opt/tyk-pump/install/inits/sysv/init.d/tyk-pump /etc/init.d/tyk-pump
    fi
fi
