#!/bin/sh

# Generated by: tyk-ci/wf-gen
# Generated on: Mon Jan 17 17:49:34 UTC 2022

# Generation commands:
# ./pr.zsh -base master -branch TD-835/Sync-releng-m4-templates -title Sync m4 release engineering templates -repos tyk,tyk-pump,tyk-analytics
# m4 -E -DxREPO=tyk-pump


if command -V systemctl >/dev/null 2>&1; then
    if [ ! -f /lib/systemd/system/tyk-pump.service ]; then
        cp /opt/tyk-pump/install/inits/systemd/system/tyk-pump.service /lib/systemd/system/tyk-pump.service
    fi
else
    if [ ! -f /etc/init.d/tyk-pump ]; then
        cp /opt/tyk-pump/install/inits/sysv/init.d/tyk-pump /etc/init.d/tyk-pump
    fi
fi
